pipeline:
  name: Rahul
  identifier: Rahul
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: bobo
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: rahulstg
        identifier: rahulstg
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    shell: Sh
                    command: |-
                      ls -R /harness
                      mvn -f /harness/pom.xml clean install
