pipeline:
  name: RRahul
  identifier: RRahul
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: automation-ci
        build: <+input>
  stages:
    - stage:
        name: build22
        identifier: build22
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: mvn clean install
                  description: desc
