pipeline:
  name: RRahul
  identifier: RRahul
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: automation-ci
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: build22
        identifier: build22
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install JDK 11
                  identifier: Install_JDK_11
                  spec:
                    shell: Bash
                    command: |
                      apt-get update
                      apt-get install -y openjdk-11-jdk
                      java -version
              - step:
                  type: RunTests
                  name: Maven Test and Reports
                  identifier: Maven_Test
                  spec:
                    shell: Bash
                    language: Java
                    buildTool: Maven
                    args: clean test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
              - step:
                  type: Run
                  name: Upload JAR
                  identifier: Upload_JAR
                  spec:
                    shell: Bash
                    command: |
                      mkdir -p .harness
                      cp target/*.jar .harness/
                    artifacts:
                      paths:
                        - .harness/*.jar
